### ISSUE TITLE
Telegram Message to chatID

### ISSUE THREAD

**Issue by oberschmuh** [Xenon-s/ioBroker.device-reminder#77]
Is it possible to send the notification to a Telegram group (chatID) in a future version?
Perhaps a Telegram custom config would be possible, where you can enter your own groups with the chatID's, similar to how you already do, e.g. at 'custom type config', only for Telegram.

Best regards
Werner

**Comment by Xenon-s** [comment]
Version 2.x

**Comment by OrlandoRose** [comment]
Group chatIDs are not in the Telegram adapter. Manual input would be nice

Orlando

**Comment by Streifi89** [comment]
Problem is, there is only an authenticated user-entry in the telegram adapter, if you identificate yourself with chatbot in private-message via telegram. If you invite your chatbot in a group, there is no option, to interact with the bot in group for security reasons and get an datapoint in iobroker as authenticated user with group-id. 

Because of this security reason, you can give the Chat-ID from group in blockly. To get the Chatgroup-ID you have to open telegram in webbrowser, open the group and get the ID from URL ;-) 
<img width="650" alt="Bildschirmfoto 2022-04-08 um 19 27 28" src="https://user-images.githubusercontent.com/103278796/162492059-458b2b50-207d-434f-9f9d-ef69699a193c.png">

Blockly:
<img width="730" alt="Bildschirmfoto 2022-04-08 um 19 29 35" src="https://user-images.githubusercontent.com/103278796/162492367-6c4e15ea-3437-4a9e-9309-55d0a8176812.png">

As you see the "-" at the beginning of the group-id is important for this feature!

**Comment by Xenon-s** [comment]
Bitte die neue Github Version (2.1.0) testen
