### ISSUE TITLE
Multiple machines connected to one plug

### ISSUE THREAD

**Issue by randomname32** [Xenon-s/ioBroker.device-reminder#87]
I want to check the status of my washing machine and the tumble dryer. This can be solved by using two smart plugs, where each of them measures the power of one of the two machines.
But is there an option to connect both machines to just one plug and then still use the device-reminder plugin to get their states?

The power profiles (power over time) of the two machines are different, so it might be possible to separate the measurement and assign it to two machines.

**Comment by Xenon-s** [comment]
Hello, no with the current adapter structure this is unfortunately not possible. T**he adapter needs consumption data per device**, if it should be possible to get the data in separately (e.g. because these data are separated by script before), it would be possible. Then you would have again for each device individual consumption values. Otherwise unfortunately not
